_crate8 = _this select 0;

clearWeaponCargoGlobal _crate8;
clearMagazineCargoGlobal _crate8;


_crate8 addWeaponCargoGlobal ["ItemCrowbar", 1];

_crate8 addWeaponCargoGlobal ["ItemToolbox", 1];

_crate8 addWeaponCargoGlobal ["ChainSaw", 1];

_crate8 addMagazineCargoGlobal ["PartEngine", 2];

_crate8 addMagazineCargoGlobal ["PartFueltank", 2];

_crate8 addMagazineCargoGlobal ["PartGeneric", 5];

_crate8 addMagazineCargoGlobal ["PartGlass", 10];

_crate8 addMagazineCargoGlobal ["PartVRotor", 2];

_crate8 addMagazineCargoGlobal ["PartWheel", 8];

_crate8 addMagazineCargoGlobal ["ItemMixOil", 2];

_crate8 addMagazineCargoGlobal ["ItemFuelBarrel", 2];

_crate8 addMagazineCargoGlobal ["ItemGenerator", 1];



