_crate6 = _this select 0;

clearWeaponCargoGlobal _crate6;
clearMagazineCargoGlobal _crate6;

_crate6 addWeaponCargoGlobal ["M9SD", 2];

_crate6 addWeaponCargoGlobal ["MakarovSD", 2];



_crate6 addMagazineCargoGlobal ["15Rnd_9x19_M9SD", 10];

_crate6 addMagazineCargoGlobal ["8Rnd_9x18_MakarovSD", 10];


_crate6 addWeaponCargoGlobal ["KSVK_DZE", 1];

_crate6 addWeaponCargoGlobal ["RPK_74", 1];

_crate6 addMagazineCargoGlobal ["Skin_GUE_Soldier_Sniper_DZ", 2];

_crate6 addMagazineCargoGlobal ["75Rnd_545x39_RPK", 5];

_crate6 addMagazineCargoGlobal ["5Rnd_127x108_KSVK", 5];

_crate6 addBackpackCargoGlobal ['DZ_Backpack_EP1', 1];
