_crate4 = _this select 0;

clearWeaponCargoGlobal _crate4;
clearMagazineCargoGlobal _crate4;



_crate4 addWeaponCargoGlobal ["Binocular_Vector", 1];

_crate4 addWeaponCargoGlobal ["ItemGPS", 1];

_crate4 addWeaponCargoGlobal ["NVGoggles", 1];

_crate4 addMagazineCargoGlobal ["Skin_TK_INS_Soldier_EP1_DZ", 2];

_crate4 addMagazineCargoGlobal ["Skin_GUE_Soldier_2_DZ", 2];


_crate4 addWeaponCargoGlobal ["MakarovSD", 2];


_crate4 addWeaponCargoGlobal ["AK_47_M", 4];

_crate4 addWeaponCargoGlobal ["FN_FAL", 4];

_crate4 addWeaponCargoGlobal ["Pecheneg_DZ", 1];

_crate4 addWeaponCargoGlobal ["RPK_74", 1];


_crate4 addMagazineCargoGlobal ["20Rnd_762x51_FNFAL", 5];

_crate4 addMagazineCargoGlobal ["8Rnd_9x18_MakarovSD", 4];

_crate4 addMagazineCargoGlobal ["30Rnd_762x39_AK47", 5];

_crate4 addMagazineCargoGlobal ["75Rnd_545x39_RPK", 5];

_crate4 addMagazineCargoGlobal ["100Rnd_762x54_PK", 5];


