_crate7 = _this select 0;

clearWeaponCargoGlobal _crate7;
clearMagazineCargoGlobal _crate7;



_crate7 addWeaponCargoGlobal ["ItemCrowbar", 1];

_crate7 addWeaponCargoGlobal ["ItemEtool", 1];

_crate7 addWeaponCargoGlobal ["ItemToolbox", 1];


_crate7 addMagazineCargoGlobal ["ItemTentDomed2", 2];

_crate7 addMagazineCargoGlobal ["PartPlywoodPack", 5];

_crate7 addMagazineCargoGlobal ["PartPlankPack", 10];


_crate7 addMagazineCargoGlobal ["bulk_PartGenericHalf", 1];

_crate7 addMagazineCargoGlobal ["bulk_ItemWireHalf", 1];

_crate7 addMagazineCargoGlobal ["bulk_ItemTankTrapHalf", 1];

_crate7 addMagazineCargoGlobal ["bulk_ItemSandbag", 1];


_crate7 addMagazineCargoGlobal ["CinderBlocks", 12];

_crate7 addMagazineCargoGlobal ["MortarBucket", 4];



