_crate5 = _this select 0;

clearWeaponCargoGlobal _crate5;
clearMagazineCargoGlobal _crate5;

_crate5 addMagazineCargoGlobal ["ItemBandage", 5];

_crate5 addMagazineCargoGlobal ["ItemMorphine", 5];

_crate5 addMagazineCargoGlobal ["ItemEpinephrine", 5];

_crate5 addMagazineCargoGlobal ["ItemPainkiller", 10];

_crate5 addMagazineCargoGlobal ["ItemWaterbottle", 5];

_crate5 addMagazineCargoGlobal ["FoodCanBakedBeans", 5];

_crate5 addMagazineCargoGlobal ["ItemAntibiotic", 5];

_crate5 addMagazineCargoGlobal ["ItemBloodbag", 5];

_crate5 addMagazineCargoGlobal ["SmokeShellPurple", 5];

_crate5 addBackpackCargoGlobal ['DZ_Backpack_EP1', 1];
